serverFiles:
  alerting_rules.yml:
    groups:
      - name: request-alerts
        rules:
          - alert: HighRequestRate
            expr: rate(prometheus_http_requests_total[5m]) > 0.25
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "More than 15 requests per minute"

alertmanager:
  config:
    global:
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: 'intheshadowsgirl@gmail.com'
      smtp_auth_username: 'intheshadowsgirl@gmail.com'
      smtp_auth_password: '{{ .Values.smtp_password }}'
      smtp_require_tls: true
    route:
      receiver: team-email
    receivers:
    - name: team-email
      email_configs:
      - to: 'selinmehmed124@gmail.com'
        send_resolved: true

  extraSecret:
    smtp-password:
      smtp_password: '{{ .Values.smtp_password }}'