# alertmanager:
#   config: |
#     global:
#       resolve_timeout: 5m

#     route:
#       receiver: webhook-receiver

#     receivers:
#     - name: webhook-receiver
#       webhook_configs:
#       - url: https://webhook.site/4bc19b38-6d41-46b2-8fce-5adefa3475d4
#         send_resolved: true

#   ## Disable default alertmanager config from being merged
#   alertmanagerSpec:
#     config: null



# alertmanager:
#   config:
#     global:
#       resolve_timeout: 5m
#     route:
#       receiver: 'webhook-receiver'
#     receivers:
#     - name: 'webhook-receiver'
#       webhook_configs:
#       - url: 'https://webhook.site/4bc19b38-6d41-46b2-8fce-5adefa3475d4'
#         send_resolved: true

# alertmanager:
#   alertmanagerSpec:
#     config: |
#       global:
#         resolve_timeout: 5m

#       route:
#         receiver: webhook-receiver

#       receivers:
#       - name: webhook-receiver
#         webhook_configs:
#         - url: https://webhook.site/4bc19b38-6d41-46b2-8fce-5adefa3475d4
#           send_resolved: true


# serverFiles:
#   alerting_rules.yml:
#     groups:
#       - name: request-alerts
#         rules:
#           - alert: HighRequestRate
#             expr: rate(prometheus_http_requests_total[5m]) > 0.25
#             for: 1m
#             labels:
#               severity: warning
#             annotations:
#               summary: "More than 15 requests per minute"

#was working at some point
alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: webhook-receiver

    receivers:
    - name: webhook-receiver
      webhook_configs:
      - url: 'https://webhook.site/4bc19b38-6d41-46b2-8fce-5adefa3475d4'
        send_resolved: true
    #   smtp_smarthost: smtp.gmail.com:587
    #   smtp_from: 'intheshadowsgirl@gmail.com'
    #   smtp_auth_username: 'intheshadowsgirl@gmail.com'
    #   # smtp_auth_password: '{{ .Values.smtp_password }}'
    #   smtp_auth_password: 'bsab ksjn srsq vocs'
    #   smtp_require_tls: true
    # route:
    #   receiver: team-email
    # receivers:
    # - name: team-email
    #   email_configs:
    #   - to: 'selinmehmed124@gmail.com'
    #     send_resolved: true

  # extraSecret:
  #   smtp-password:
  #     smtp_password: '{{ .Values.smtp_password }}'