services:

  # Frontend Nginx app
  app:
    build:
      context: ../app  # or wherever your frontend folder is
      dockerfile: Dockerfile
      args:
        APP_SERVICE_URL: http://app-service:5000
    ports:
      - "8080:80"
    depends_on:
      - app-service
    environment:
      APP_SERVICE_URL: http://app-service:5000

  # Backend app-service
  app-service:
    build:
      context: ../app/app-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - model-service

  # ML model service
  model-service:
    build:
      context: ../model-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MODEL_URL: https://github.com/remla25-team11/model-training/releases/download/v0.0.1/c2_Classifier_Sentiment_Model
      VECTORIZER_URL: https://github.com/remla25-team11/model-training/releases/download/v0.0.1/c1_BoW_Sentiment_Model.pkl
