version: "3.9"

services:
  model-service:
    build:
      context: ../model-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
    - MODEL_URL=https://github.com/remla25-team11/model-training/releases/download/v0.0.1/c2_Classifier_Sentiment_Model
    - VECTORIZER_URL=https://github.com/remla25-team11/model-training/releases/download/v0.0.1/c1_BoW_Sentiment_Model.pkl
    container_name: model-service

  frontend:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      URL_MODEL_SERVICE: http://model-service:8080/predict
      URL_MODEL_VERSION: http://model-service:8080/model/version
    depends_on:
      - model-service
    container_name: frontend
