{
 "title": "Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(request_latency_seconds_sum[5m]))\n/\nsum by (endpoint) (rate(request_latency_seconds_count[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentiment Predictions Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sentiment_predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(webapp_requests_total{endpoint=\"http\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}