apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: app-service
          image: ghcr.io/remla25-team11/app-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: URL_MODEL_SERVICE
              value: http://model-service:8000/predict
            - name: URL_MODEL_VERSION
              value: http://model-service:8000/version
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  type: NodePort
  selector:
    app: app-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: status-port
      port: 15090
      targetPort: 15090
