apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: app-service  
  endpoints:
    - port: http     
      path: /api/metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default           

