apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: app-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
