apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-istio-traffic
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: istio.rules
      rules:
        - alert: HighIstioTraffic
          expr: rate(istio_requests_total{destination_workload="app-service", reporter="destination"}[1m]) > 0.25
          for: 120s
          labels:
            severity: warning
          annotations:
            summary: "High traffic to app-service"
            description: "Istio reports more than 15 requests per minute to app-service."
