apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-istio-proxy
  namespace: monitoring   # Prometheus namespace
  labels:
    release: kube-prometheus-stack

spec:
  selector:
    matchLabels:
      app: app-service
  namespaceSelector:
    matchNames:
      - default           # Namespace where app-service runs
  endpoints:
    - port: status-port    # Must match the port name on app-service's Service that exposes Istio proxy metrics
      path: /stats/prometheus
      interval: 15s
      scheme: http
