apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxies
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  selector: {}  

  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
      scheme: http
