apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-traffic-alert
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   
spec:
  groups:
  - name: traffic.rules
    rules:
    - alert: HighRequestRate
      expr: rate(request_latency_seconds_count[1m]) < 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High request rate !"
        description: "More than 15 requests per min for 2 min"
