# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: request-alerts
#   namespace: monitoring
# spec:
#   groups:
#     - name: request-alerts
#       rules:
#         - alert: HighRequestRate
#           expr: rate(prometheus_http_requests_total[5m]) > 0.25
#           for: 1m
#           labels:
#             severity: warning
#           annotations:
#             summary: "More than 15 requests per minute"

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: example.rules
    rules:
    - alert: AlwaysFiringChange
      expr: vector(1)
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "This is a test alert that always fires"
        description: "The vector(1) expression will always evaluate to true"
