{{- $componentConfig := .Values.nginxFrontendV1 -}}
{{- $componentName := $componentConfig.nameOverride | default "nginx-frontend-v1" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.fullname" . }}-{{ $componentName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "app-chart.componentLabels" (dict "root" . "componentName" $componentName "versionLabel" $componentConfig.versionLabel) | nindent 4 }}
spec:
  replicas: {{ $componentConfig.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $componentName }}
  template:
    metadata:
      labels:
        {{- include "app-chart.componentLabels" (dict "root" . "componentName" $componentName "versionLabel" $componentConfig.versionLabel) | nindent 8 }}
    spec:
      containers:
        - name: {{ $componentName }}
          image: {{ include "app-chart.imageName" (dict "global" .Values.global "componentImage" $componentConfig.image) }}
          imagePullPolicy: {{ $componentConfig.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $componentConfig.service.targetPort }}
              protocol: TCP
          env:
            {{- /* This is the robust fix using toYaml */}}
            {{- $root := . -}}
            {{- $envVars := list -}}
            {{- range $key, $value := $componentConfig.env -}}
              {{- $var := dict "name" $key "value" (tpl $value $root) -}}
              {{- $envVars = append $envVars $var -}}
            {{- end -}}
            {{- $envVars | toYaml | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
